### ISSUE TITLE
Local function "rotate_and_place" initialized too late

### ISSUE THREAD

**Issue by SmallJoker** [v-rob/bridger#3]
Affected code:
https://github.com/v-rob/bridger/blob/2ba4428f7059cd2991f3ea857e061ae86fd34368/nodes.lua#L65-L88

A few lines above, this function is called. On certain Lua(JIT) versions (don't know which exactly), this results in an error as soon the function is called because it was not known by the time when Lua parsed the file.

Full error: https://forum.minetest.net/viewtopic.php?p=326374#p326374

**Comment by v-rob** [comment]
Fixed with 6fb646a.
